# Generated by Django 2.1.7 on 2019-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
