# Generated by Django 2.1.7 on 2019-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20190304_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='phone',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
