# Generated by Django 2.1.7 on 2019-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20190304_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='file',
            new_name='curriculum',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='presentation_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
