# Generated by Django 2.1.7 on 2019-03-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20190304_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='title',
            new_name='title_the_presentation_letter',
        ),
    ]
